services:
  backend:
    container_name: backend
    env_file:
      - .env
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - SESSION_MANAGER=${SESSION_MANAGER}
    volumes:
      - ./backend/public/img:/public/img


    
  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - SESSION_MANAGER=${SESSION_MANAGER}

  db:
    image: postgres:16
    ports:
      - "5433:5433"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "port=5433"] 
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    logging:  
      driver: none


volumes:
  postgres-data:
    driver: local

    