services:
  backend:
    ports:
      - "3001:3001"
    networks:
      - app-network
    labels: []  # verwijder Traefik labels

  frontend:
    ports:
      - "3000:3000"
    networks:
      - app-network
    labels: []  # verwijder Traefik labels

networks:
  app-network:
    external: false
  traefik:
    driver: bridge